### PR TITLE
Make a folder for relations

### PR DESCRIPTION
**Pull request by mortberg**
and move neg, dec and Hedberg's theorem there. Also rename NTypes.agda to HLevels.agda

### CODE REVIEW

**Comment by mortberg** [comment]
I think this resolves https://github.com/agda/cubical/issues/39 or are there any more recommendations from the standard library that I should consider?

**Comment by ice1000** [comment]
So your blog post in the README is getting deprecated due to the module/function definition changes.

FYI I have a personal maintained version on my blog which is up-to-date: https://ice1000.org/lagda/CubicalAgdaLiterate.html

**Comment by mortberg** [comment]
> So your blog post in the README is getting deprecated due to the module/function definition changes.
> 
> FYI I have a personal maintained version on my blog which is up-to-date: https://ice1000.org/lagda/CubicalAgdaLiterate.html

Thanks for keeping a version up to date! I should update the README to reflect the current structure

**Comment by MatthewDaggitt** [comment]
Looks good. Sorry I didn't get to this beforehand.

**Pull request merged**
