### PR TITLE
improve group induced structure

### PR DESCRIPTION
**Pull request by ecavallo**
Make it so that only properties are induced, not operations. This should be done for AbGroup also.

### CODE REVIEW

**Comment by thomas-lamiaux** [comment]
I don't remember exactly what was said but I think you were saying that it would be pratical to have a raw ring structure ?
But there is https://github.com/agda/cubical/blob/master/Cubical/Algebra/CommRingSolver/RawRing.agda in the library, isn't what you were talking about ?

**Comment by mortberg** [comment]
Yeah, but I don't know how useful it is... I'll implement the corresponding induced structure lemmas for rings today. If I don't run into any problems I guess we don't really need raw rings

**Comment by mortberg** [comment]
@ecavallo  The CI fails. Seems to be something about cohomology... I guess @aljungstrom  was relying on the bad version of the lemma?

**Comment by mortberg** [comment]
I'll investigate locally and hopefully make a PR fixing everything

**Comment by aljungstrom** [comment]
The issue with this approach is of course that we don't always care about the unit and the inverse of the induced group (this is the case in The DirectProof file). I can fix it (and I probably should for various reasons) but doesn't it make more sense to have both versions of the induced group?

**Comment by mortberg** [comment]
> The issue with this approach is of course that we don't always care about the unit and the inverse of the induced group (this is the case in The DirectProof file). I can fix it (and I probably should for various reasons) but doesn't it make more sense to have both versions of the induced group?

Yeah, having both version could make sense. But I'm surprised you don't care about the unit and inverse of the induced group... Don't they pop up at some later point in the proof? With the current approach they are most likely defined using useless transports which will be annoying to get rid of everywhere...

**Comment by mortberg** [comment]
> They never show up actually. I am only using the induced stuff to be able to trace my term of interest step by step rather than in one go, so I am not really relying on much of the group structure on pi*. I just need to know that the maps are homomorphisms and that pi* is a group -- nothing more than that really.
> 
> In this particular case, I'll probably want to know what the other stuff in pi* is for future work, so I have no problem filling the holes if we decide to only use Evan's definition. But it still feels reasonable to keep both: using induced groups in order to split up longer proofs into smaller pieces is a really neat, and not having to specify additional data of course simplifies things.

Ok, fair enough! I'm convinced that we should have two versions of the induced structure, one where the user can specify as much of the raw structure as possible and one where they can specify the minimal amount

**Comment by thomas-lamiaux** [comment]
Then a warning should be add so as people don't think it is reduced but equivalent version like for group morphism

**Comment by mortberg** [comment]
> Then a warning should be add so as people don't think it is reduced but equivalent version like for group morphism

Well, the two induced groups are equivalent as the unit and inverse are always unique. But the operations are not definitionally the same. I'll add a comment about this

**Comment by thomas-lamiaux** [comment]
This is true that they are equivalent. Do we have a word for two structures that are equivalent but have different equality or computation rules ? For instance Vec and FinVec ?

**Comment by mortberg** [comment]
> This is true that they are equivalent. Do we have a word for two structures that are equivalent but have different equality or computation rules ? For instance Vec and FinVec ?

I can't think of a great name for this... Anyway,to make things even more confusing univalence implies that two such types are equal, but that of course doesn't mean that they are the same :-)

**Comment by mortberg** [comment]
I've implemented @aljungstrom 's suggestion now on https://github.com/agda/cubical/pull/827, so I'll close this PR as the other will supersede it once I've figured out how to get the induced ring structure to work

**Pull request closed without merging**
