### PR TITLE
Create Synthetic.agda

### PR DESCRIPTION
**Pull request by pnlph**
First PR. Create Papers folder and the code for the synthetic cubical paper. See issue #347 

Preserved as much as could the notation of the original paper.

Let's see how it goes :-)

### CODE REVIEW

**Comment by mortberg** [comment]
Very nice, thank you! Your file contains some whitespace in the end which Travis complains about. Have a look at https://github.com/agda/cubical/blob/master/CONTRIBUTING.md to see how you can easily fix it.

**Comment by pnlph** [comment]
The test is still not passing, I double-checked that there are not whitespaces at the end of the lines. Could be the problem that I am using Atom? I also turned all the spaces to tabs with the `whitespace` package.

With whitespace is meant leaving one or more empty spaces at the end of a line, right?

**Comment by mortberg** [comment]
Yes, you can't have any empty spaces at the end of lines. Try loading the file with emacs and the run "M-x delete-trailing-whitespace"

**Comment by guillaumebrunerie** [comment]
> I also turned all the spaces to tabs with the `whitespace` package.

I don’t know if that’s the issue, but it’s usually better to use spaces instead of tabs.

**Comment by pnlph** [comment]
Finally Travis is happy, everything fixed. Thank you for the guidance.

**Comment by mortberg** [comment]
Great, thank you for this! If you feel like doing more of it I think it would be useful to have this for the Cubical Agda paper itself as well.

**Pull request merged**
