### PR TITLE
Pulling back an equivalence relation along a function

### PR DESCRIPTION
**Pull request by MatthiasHu**
This PR is a small contribution that shows that equivalence relations can be pulled back along functions.

### CODE REVIEW

**Comment by felixwellen** [comment]
I don't get the name "on". Maybe it would be better to be more verbose?

**Comment by MatthiasHu** [comment]
I took the name from Haskell: https://hackage.haskell.org/package/base-4.16.3.0/docs/Data-Function.html#v:on

But I understand that it is not optimal. Would it be an option to give the module a name (such as `PulledBackRelation`) so that one can write the following?
```agda
_~_ = ...

_~'_ = on fst _~_
  where open PulledBackRelation
```

**Comment by felixwellen** [comment]
Hm. So "on" means "along"?
If I read "on fst R" somewhere, I would have no idea what it is about. What about just renaming "on" to "pulledbackRel" or "relPullback" or something like this?

**Comment by MatthiasHu** [comment]
Ok, I went with `pulledbackRel`.

**Review by felixwellen — APPROVED** [review]
Thanks! Looks good to me now.

**Pull request merged**
