### PR TITLE
(WIP) Int is a Commutative Ring.

### PR DESCRIPTION
**Pull request by xekoukou**
I had to make extensive changes  to the Ring , CommRing structures. I haven't checked if it breaks things.

I  will update this  when the structures are stabilized by the authors of this library.

I split  the structures into RawRingStr RingStr and CommRingStr. And I  updated the DUARel accordingly.

Then, I used the  proofs that BiIntZ is a comm. ring , to  do the same for Z, by using the DUARels.

### CODE REVIEW

**Comment by xekoukou** [comment]
Related https://github.com/agda/cubical/pull/461
and
https://github.com/agda/cubical/pull/461/files#r577129000

**Comment by felixwellen** [comment]
I got an error on running make:
     Checking Cubical.ZCohomology.GroupStructure (/home/felix/repos/cubical/Cubical/ZCohomology/GroupStructure.agda).
/home/felix/repos/cubical/Cubical/ZCohomology/GroupStructure.agda:23,35-57
The module Cubical.Algebra.Group doesn't export the following:
  ℤ

**Comment by xekoukou** [comment]
If you want to look at what I did, only check this [file](https://github.com/xekoukou/cubical/blob/IntCommRing/Cubical/Algebra/Ring/Instances/Int.agda)

and maybe [this](https://github.com/xekoukou/cubical/blob/0552b4966f564ca3a80fe075a5cd7393a589322d/Cubical/Algebra/Ring/Base.agda#L251), where I split the Duarel into two parts.

I didn't update everything , that is why make complains, also there are merge conflicts.

Before merging, someone needs to decide which will be the default structures, rawmonoid, monoid, commmonoid, etc.

I can't do this myself.

**Comment by mortberg** [comment]
Isn't the main result already in the library: https://github.com/agda/cubical/blob/master/Cubical/Algebra/CommRing/Instances/Int.agda#L12 ? 

The reorganization of the structures is something we've been thinking about doing and @ecavallo started doing it for all algebraic structures but never finished...

**Comment by mortberg** [comment]
> Isn't the main result already in the library: https://github.com/agda/cubical/blob/master/Cubical/Algebra/CommRing/Instances/Int.agda#L12 ?
> 
> The reorganization of the structures is something we've been thinking about doing and @ecavallo started doing it for all algebraic structures but never finished...

Oh wait, you're giving the Ring instance. I guess it would be better to make it the same way as the CommRing instead of transporting it. My experience is that the non-higher version of Int is actually the easiest to work with, so I think it should be the default which all other definitions should inherit their properties from

**Comment by mortberg** [comment]
This has been open for very long and I don't think we've reached any consensus about it. The main result of the PR is now in the library, but proved directly so I'm going to close this now. 

The reorganization of the algebraic structures seems like a very good idea, but it should be done in separate PRs after some careful considerations to ensure that inference and automation works properly. Also, for the moment we've added some new lemmas with the current design that should make the proofs in this PR easier to streamline without rewriting the algebraic hierarchy: https://github.com/agda/cubical/blob/master/Cubical/Algebra/Ring/Base.agda#L265

**Pull request closed without merging**
