### PR TITLE
Add TotalSpace and Surjection

### LINKED ISSUE #217: Surjective
I wrote following, (HoTT section 4.6), last two functions are inverse due everything being `isProp`,
should I create ea PR adding `Cubical.Foundation.Surjection`?

```agda
module Surjective {ℓ ℓ'} {A : Set ℓ} {B : Set ℓ'} where
  isSurjection : (A →  B) → Type _
  isSurjection f = ∀ (b : B) → ∥ fiber f b ∥

  isSurjectionIsProp : (f : A → B) → isProp (isSurjection f)
  isSurjectionIsProp _ = propPi λ _ → squash

  isEquiv→isEmbedding : (f : A → B) → isEquiv f → isEmbedding f
  isEquiv→isEmbedding f e = hasPropFibers→isEmbedding λ b → isContr→isProp (equiv-proof e b)

  isEquiv→isSurjection : (f : A → B) → isEquiv f → isSurjection f
  isEquiv→isSurjection f e b = ∣ fst (equiv-proof e b) ∣

  isEquiv→isEmbedding×isSurjection : (f : A → B) → isEquiv f → isEmbedding f × isSurjection f
  isEquiv→isEmbedding×isSurjection f e = isEquiv→isEmbedding f e , isEquiv→isSurjection f e

  isEmbedding×isSurjection→isEquiv : (f : A → B) → isEmbedding f × isSurjection f → isEquiv f
  equiv-proof (isEmbedding×isSurjection→isEquiv f (emb , sur)) b =
    inhProp→isContr (recPropTrunc fib' (λ x → x) fib) fib'
    where
      hpf : hasPropFibers f
      hpf = isEmbedding→hasPropFibers emb

      fib : ∥ fiber f b ∥
      fib = sur b

      fib' : isProp (fiber f b)
      fib' = hpf b
```

### LINKED ISSUE #218: Total space
I wrote following (HoTT lemma 4.8.2, yet different, more direct proof)

```agda
module TotalSpace {ℓ} {A B : Set ℓ} (f : A → B) where
  Total = Σ B \ b → fiber f b

  A→Total : A → Total
  A→Total a = f a , a , refl

  Total→A : Total → A
  Total→A (b , a , p) = a

  Total→A→Total : ∀ t → A→Total (Total→A t) ≡ t
  Total→A→Total (b , a , p) i = p i , a , λ j → p (i ∧ j)

  A→Total→A : ∀ a → Total→A (A→Total a) ≡ a
  A→Total→A a = refl

  A≡Total : A ≡ Total
  A≡Total = isoToPath (iso A→Total Total→A Total→A→Total A→Total→A)

  -- Lemma 4.8.2
  A≃Total : A ≃ Total
  A≃Total = isoToEquiv (iso A→Total Total→A Total→A→Total A→Total→A)

  Total≃A : Total ≃ A
  Total≃A = isoToEquiv (iso Total→A A→Total A→Total→A Total→A→Total)

open TotalSpace public
```

I haven't found this in `cubical`, should it be added (what would be good module name / lemma names?)

### PR DESCRIPTION
**Pull request by phadej**
Resolve #217
Resolve #218

### CODE REVIEW

**Comment by ecavallo** [comment]
Is there a more descriptive name we could use for `Total`? In general, the total space of a family `B : A → Type` is the type `Σ A B`. The definition in `TotalSpace` is specifically the total space of the family `fiber f : B → Type`.

**Comment by phadej** [comment]
@ecavallo I don't know if renaming `Total` to `FiberBundle` would make it less wrong. (Technically I guess the `fst` would be the fiber bundle. In that terminology, the `A` **is** however a total space of *fiber bundle*, not `f`.). Another alternative would be to rename `Total` to `Total-fiber`, then we will have

```agda
A≡Total-fiber : (f : A → B) → Lift A ≡ Total-fiber f
```

which -- I guess -- reads less wrong.

Disclaimer: I don't really don't know any topology nor homotopy theory, I'm learning this stuff "backwards", from type-theory.

**Comment by ecavallo** [comment]
`Total-fiber` (or `TotalFiber`) sounds good to me.

> Disclaimer: I don't really don't know any topology nor homotopy theory, I'm learning this stuff "backwards", from type-theory.

We're in the same boat there :)

**Comment by phadej** [comment]
I'll wait until @Saizan approves the color of the bikeshed, and will rename if `Total-fiber` or `TotalFiber` are ok.

**Comment by Saizan** [comment]
`Total-fiber` looks better to me. Also travis tells me there's some whitespace problems in `TotalSpace.agda`.

**Comment by phadej** [comment]
Renamed to `Total-fiber`, travis is happy too.

**Comment by Saizan** [comment]
Great, thanks for the PR!

**Pull request merged**
