### PR TITLE
Prove false

### PR DESCRIPTION
**Pull request by ice1000**
Prove false.

### CODE REVIEW

**Comment by ice1000** [comment]
Note: some of the codes here do not belong to me. They come from dram, where dram was inspired by someone in the IRC.

**Comment by dramforever** [comment]
The proof that `--with-K` and `--cubical` leads to inconsistency came from `tomjack` on IRC: https://www.irccloud.com/pastebin/NFolVTgR/

**Comment by mortberg** [comment]
I'm not sure if we should merge this... Maybe it is interesting to newcomers? But the fact that UIP/K is incompatible with univalence is very well-known

**Comment by Alizter** [comment]
If it is going to be useful for newcomers, then perhaps it will be more useful if we add some more comments talking about axiom K, what that means and how the proof works. I don't see any reason not to merge this.

**Comment by mortberg** [comment]
The reason not to merge it is that it is not very useful to have a proof of false from two principles that are well known to be contradictory. But I do agree that if it is properly documented then it might be instructive for beginners.

**Comment by Alizter** [comment]
Perhaps add a README to WithK in order to emphasize that importing any of these files is very contradictory.

@mortberg I would agree that for people interested in HoTT, univalence and K being incompatible is well known, however if I understand correctly, the point of cubical agda is not just to be another model of HoTT but rather as a programming languages with HITs. There are many people interested in programming languages who might not really care about univalence (yet).

Say for example somebody unknowingly used K everywhere in their agda code and were interested in porting it to cubical agda for whatever reason. I think this file can be your canonical example of what goes wrong.

Just some ideas.

**Comment by ice1000** [comment]
> Perhaps add a README to WithK in order to emphasize that importing any of these files is very contradictory.

I got banner comments for this fact. Is a README really needed? I'm not sure what should I put into the README though.

**Comment by Alizter** [comment]
@ice1000 I would just put a warning about importing these files. The readme would be seen when browsing on github at least.

As I understand @mortberg thinks this is not really useful since it is so well known.

I am trying to say that it would be instructional, especially for people unfamiliar with univalence. The other issue is if I was new to cubical agda, withK isn't really a folder that grabs my attention.

So perhaps this should be part of an intro or a course on cubical agda rather than part of the main library?

**Comment by ice1000** [comment]
> I'm not sure if we should merge this... Maybe it is interesting to newcomers? But the fact that UIP/K is incompatible with univalence is very well known

Yes, it is interesting to newcomers! At least it takes you some time to come up with the proof of `ptoc-ctop`.

**Comment by ice1000** [comment]
> @ice1000 I would just put a warning about importing these files. The readme would be seen when browsing on github at least.

These files cannot be imported with the `--safe` flag, while other files (with a `--safe` flag) can.

**Comment by ice1000** [comment]
I have split the without-K definitions used in `WithK` into a separate safe module.

**Comment by ice1000** [comment]
Travis fails with:

```
[336 of 373] Compiling Agda.TypeChecking.Coverage ( src/full/Agda/TypeChecking/Coverage.hs, dist/build/Agda/TypeChecking/Coverage.o )
cabal: Leaving directory '.'
Failed to install Agda-2.6.1
cabal: Error: some packages failed to install:
Agda-2.6.1 failed during the building phase. The exception was:
ExitFailure (-9)
This may be due to an out-of-memory condition.
The command "cabal install" failed and exited with 1 during .
```

**Comment by Saizan** [comment]
I think the content of `Cubical.WithK.WithoutK` should actually be moved to `Cubical.Data.Equality`, as it is useful to have the equivalence between paths and inductive equality.

The other modules can also provide more context in their comments, like probably citing the HoTT book, and how `--safe` prevents mixing the two flags this way.

**Comment by ice1000** [comment]
> I think the content of `Cubical.WithK.WithoutK` should actually be moved to `Cubical.Data.Equality`, as it is useful to have the equivalence between paths and inductive equality.
> 
> The other modules can also provide more context in their comments, like probably citing the HoTT book, and how `--safe` prevents mixing the two flags this way.

Done

**Pull request merged**
