### PR TITLE
WIP: Coproduct of AbGroups

### PR DESCRIPTION
**Pull request by felixwellen**
Defines the coproduct of a type-indexed family of abelian groups as a HIT. 
WIP: Show the universal property.

### CODE REVIEW

**Comment by thomas-lamiaux** [comment]
I think that this something that I have already added to the library as https://github.com/agda/cubical/blob/master/Cubical/Algebra/DirectSum/Base.agda ? With an instantiation here for abelian group here https://github.com/agda/cubical/blob/master/Cubical/Algebra/AbGroup/Instances/DirectSum.agda

incl              = base
epsilon        = 0
⊕               = add
inclPres+    = base-add
assoc         = assoc
comm        = comm
identityᵣ     = IdR
trunc         = trunc
--
⊖_  and invᵣ are not neccesary as they can be lifted from the definition
--
In my definition there is also a base-neutral in file that is useful when working to have only one zero

**Comment by felixwellen** [comment]
Ok - good.

**Comment by felixwellen** [comment]
I'll stop to work on that until #798 is merged. Then I might add the universal property to the definition of 'DirectSum's on that branch/master.

**Comment by thomas-lamiaux** [comment]
In #798 I have added the Universal Property for the direct sum because we needed to prove it to make sure it was the "good direct sum". So I don't know if there is still something you want to add in this PR ?

**Pull request closed without merging**
