### PR TITLE
General cohomology

### PR DESCRIPTION
**Pull request by felixwellen**
Define cohomology of a type with coefficients in a spectrum dependent over the type.
* Define AbGroup structure
* Define application of cohomology functors to maps between types

### CODE REVIEW

**Comment by felixwellen** [comment]
@aljungstrom: this is the general definition I was talking about a while ago.

**Comment by aljungstrom** [comment]
Yes, now I see what you meant:-) Very nice!

**Comment by kangrongji** [comment]
The sequence`CohomClasses` forms spectrum right? What about to define "cohomology spectrum" first, then using the theory of stable homotopy groups of spectrum to treat cohomology groups... That needs far more work ,though.

**Comment by felixwellen** [comment]
There is now a proof that `CohomClasses X A` is a spectrum in #731

**Comment by kangrongji** [comment]
I see. That's nice!

**Comment by kangrongji** [comment]
Btw, do you have plan to formalize Serre spectral sequence? I've been always interested in it and that's on my wish list from the very beginning.

**Review by mortberg — APPROVED** [review]
Looks good! Just check the funExtEquiv thing

**Comment by mortberg** [comment]
Should I merge once the CI is finished?

**Comment by felixwellen** [comment]
Yes!

**Pull request merged**
