### PR TITLE
DeltaInt

### PR DESCRIPTION
**Pull request by ice1000**
Define Int as the diff of two Nats

### CODE REVIEW

**Comment by Alizter** [comment]
I don't think this is equivalent to the integers.

**Comment by mortberg** [comment]
> I don't think this is equivalent to the integers. More specifically the missing coherence conditions in your attempt at an equivalence are probably precisely what you are missing in the definition.

Why? It's essentially just the integers defined as the ring of differences of nat...

It would be nice to complete the proof that they are equivalent to the non-HIT integers. Maybe it would make help to try to prove that equality is decidable so that we see that they form a set.

**Comment by ice1000** [comment]
> Maybe it would make help to try to prove that equality is decidable so that we see that they form a set.

Well, I was thinking about proving `DeltaInt = Int` and use substitute `isSet Int` to `isSet DeltaInt`.

**Comment by ice1000** [comment]
This is like defining the thing in #96 with a HIT.

**Comment by ice1000** [comment]
The CI fails with

```
Creating package registration file: /tmp/pkgConf-Agda-2.6308846135608580149.1
src/data/lib/prim/Agda/Builtin/Bool.agdai: copyFile: does not exist (No such
file or directory)
cabal: Leaving directory '.'
Failed to install Agda-2.6.1
```

which is not my fault.

**Comment by ice1000** [comment]
Well, I lost my work by jumping through branches and doing `git reset --hard`s... I'll try to take them back (or rewrite them 😭)

**Pull request closed without merging**
