### PR TITLE
Terminal algebra

### PR DESCRIPTION
**Pull request by felixwellen**
Construct the terminal R-algbera (=zero ring). Use the terminal ring.

### CODE REVIEW

**Comment by mortberg** [comment]
Looks good! Thanks for generalizing the terminal ring. I would suggest you add the category of commutative algebras with its terminal object in `Cubical.Categories.Instances.CommAlgebras` as well.

**Comment by ice1000** [comment]
The CI problem, if I'm right, should be fixed by #690

**Comment by ice1000** [comment]
Yaaas!

**Comment by felixwellen** [comment]
Thanks!

**Pull request merged**
