### PR TITLE
Equational reasoning for composition of group isos + some cleanup of ZCohomology

### PR DESCRIPTION
**Pull request by aljungstrom**
I guess the title of this PR is pretty self explanatory...

The cleaup of ZCohomology: 
Added equational reasoning.
Shorter for of some trivial cohomology groups using the definition of truncations.

@mortberg I am really not sure what is going on here. The ZCohomology.Groups.Wedge.Agda now takes like 40 seconds to check. I tried making arguments implicit, explicit and defining the vSES using copatterns, but nothing seems to help. Seems weird that this would be caused by the equational reasoning I added in e.g. ZCohomology.Sn

### CODE REVIEW

**Comment by mortberg** [comment]
There are conflicts...

**Comment by aljungstrom** [comment]
> There are conflicts...

I think github is just being slow. The files changed doesn't seem to take the last merged branch into account.

**Comment by mortberg** [comment]
Very strange that things got slower. Will try here

**Comment by mortberg** [comment]
New PR coming, so closing this one

**Pull request closed without merging**
