### PR TITLE
Added agda-2.6.3 in flakes

### PR DESCRIPTION
**Pull request by guilhermehas**
Cubical Agda in Nix is compiled using Agda 2.6.3.

### CODE REVIEW

**Comment by felixwellen** [comment]
Nice!
I don't understand why the old ci-ubuntu job doesn't run - do you know?

**Comment by felixwellen** [comment]
More questions: 
* How the version of agda picked? Right now, we should use the branch release-2.6.3 for testing and we should switch eventually to the tag v2.6.3 which doesn't exist yet.
* How do nix flakes compose? If I have a project, that uses flake A and flake B, which both have agda defined as outputs, which agda will be available in the environment I get in the end?

**Comment by guilhermehas** [comment]
> Nice! I don't understand why the old ci-ubuntu job doesn't run - do you know?
No, I don't know

> * How the version of agda picked? Right now, we should use the branch release-2.6.3 for testing and we should switch eventually to the tag v2.6.3 which doesn't exist yet.
The version of file is in this Line:
https://github.com/agda/cubical/blob/7f947d86ad872f70bdb63aed852745eefa97d847/flake.nix#L10
For your example, the line will be:
```nix
inputs.agda.url = "github:agda/agda/?ref=v2.6.3";
```

> * How do nix flakes compose? If I have a project, that uses flake A and flake B, which both have agda defined as outputs, which agda will be available in the environment I get in the end?
It is composed using overlay:
For example:
```nix
overlays = [ overlayAgda2 overlayAgda3 ]
pkgs = import nixpkgs { inherit overlays}
```
Nixpkgs have Agda1, overlayAgda2 has Agda2 and overlayAgda3 has Agda3.
I think that in the end, Agda3 will be used.

@MatthiasHu maybe can help if I explained anything wrong.

**Comment by felixwellen** [comment]
Thanks for explaining and for pointing me to the agda-version - I just overlooked that line in the diff...

**Comment by MatthiasHu** [comment]
> Nice! I don't understand why the old ci-ubuntu job doesn't run - do you know?

That is because the ci-ubuntu workflow is configured to run on pull requests into master, but this is not a pull request into master. :-)

**Comment by MatthiasHu** [comment]
I was a bit confused why we have two versions of nixpkgs in `flake.lock` now, `nixpkgs` and `nixpkgs_2`. I think this is because the Agda flake (in the version specified in our flake.flake) specifies (in its flake.lock) a different version of nixpkgs than our flake.lock does. I am not sure if this is the way it is supposed to be when you compose flakes, but I also don't see a good way to avoid it.

**Comment by MatthiasHu** [comment]
I think I understand now that we could declare that our nixpkgs input `follows` Agda's nixpkgs -- or the other way round. But it does not seem to be necessary: ["[...] it is generally not useful to eliminate transitive nixpkgs flake inputs [...]"](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-flake.html#flake-inputs). We could still do it for flake-utils, but probably it is not important.

**Pull request merged**
