### PR TITLE
Sip pr

### PR DESCRIPTION
**Pull request by mzeuner**
We give a cubical proof of the structure identity principle, as formulated in the lecture notes of Martin Escardó:

https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/HoTT-UF-Agda.html#sns

Hopefully, we can compute nice things with it. A first rather straightforward implementation of the original proof can be found in the Experiments folder in the file EscardoSIP, a more direct proof using more cubical methods is in the SIP file in the Foundations folder. This file also contains monoids as an example application.

### CODE REVIEW

**Comment by mortberg** [comment]
There's some whitespace issues making Travis upset. Can you please fix it? (Emacs has a great command: M-x delete-trailing-whitespac)

**Comment by mzeuner** [comment]
Thanks, that apparently did the job.

**Comment by mortberg** [comment]
Thanks! I'll merge this now

**Comment by mortberg** [comment]
I noticed that the SIP file wasn't in Foundations.Everything. Added it now

**Pull request merged**
