### PR TITLE
Add some Nat properties and ordering on Nat

### PR DESCRIPTION
**Pull request by dolio**
I've been trying to prove that the ordering is a proposition, but haven't figured out how yet.

I've also been fooling around with using the ordering in a couple different ways to define finite sets, since indexed inductive definitions aren't available yet.

Thoughts?

### CODE REVIEW

**Comment by mortberg** [comment]
If you want to prove that <= is prop valued then you need to note that the k in <= is unique and then use the characterization of equality in Sigma types where the second component is a proposition: https://github.com/agda/cubical/blob/master/Cubical/Foundations/HLevels.agda#L98

**Comment by mortberg** [comment]
PS: You will also need to use that nat is a set.

**Comment by dolio** [comment]
Okay, that was the piece I needed. It's added now.

**Comment by 3abc** [comment]
CI failed. You need to rename the `+-comm` for integers.

**Comment by dolio** [comment]
Okay. I tried running the check locally, but it failed on other stuff (constraint solving cubical stuff, I think). I'll try to get things fixed up.

**Comment by Saizan** [comment]
@dolio things built fine here, so I renamed `+-comm` and merged.

**Pull request merged**
