### PR TITLE
Useful functions in Algebra such as Op2 = A -> A -> A 

### PR DESCRIPTION
**Pull request by guilhermehas**
I created some functions that can be useful in the Cubical Library, such as Op1 and Op2.

### CODE REVIEW

**Comment by felixwellen** [comment]
Sorry for the long wait! 
Can you explain, what the purpose of your changes is?

**Comment by guilhermehas** [comment]
This idea came from Agda Stdlib:
https://github.com/agda/agda-stdlib/blob/8ffc4cccf64ca1626f866ad0bc0f7d965e705d6b/src/Algebra/Core.agda#L18

It is to reduce the number of characters and make the code more succint.

**Comment by mortberg** [comment]
> This idea came from Agda Stdlib: https://github.com/agda/agda-stdlib/blob/8ffc4cccf64ca1626f866ad0bc0f7d965e705d6b/src/Algebra/Core.agda#L18
> 
> It is to reduce the number of characters and make the code more succinct.

Is this used a lot in the standard library? It doesn't seem very useful to me and I definitely find `A → A → A` a lot more informative and readable than `Op₂ A`...

**Comment by felixwellen** [comment]
I agree with Anders, I am also a lot faster at recognizing ```A → A → A``` and someone new to this part of the library would actually have to look up the op-notation to check if it is really just a function type. 
I don't know why the stdlib is using this notation - I always assumed it is used for some kind of abstraction somewhere, e.g. functions using ```Op₂``` as an input datum.

**Comment by felixwellen** [comment]
Since this PR is only about introducing the op-notation, I'm going to close it now. If you think we misunderstood/missed something, feel free to continue discussing or reopen it.

**Review by felixwellen — COMMENTED** [review]
Closed.

**Pull request closed without merging**
