### PR TITLE
[work-in-progress] Add abelian categories

### PR DESCRIPTION
**Pull request by barrettj12**
This PR defines abelian categories in the file `Categories.Abelian.Base`.
The definition depends on (co)products, which I have defined in `Categories.Limits.Product` and `Categories.Colimits.Coproduct`.

I also defined:
- (co)equalisers in `Categories.Limits.Equaliser` and `Categories.Colimits.Coequaliser`
- discrete categories in `Categories.Instances.Discrete`

but didn't end up using these for `Abelian`. I could potentially move these into a separate pull request.

**Don't merge yet** - I still have some things to tidy up, but feedback and contributions are welcome.

### To do:
- [ ] Fix module issues - I'm running into problems having the `Precategory C` as an implicit argument, then it can't work out what `C` should be, so I have to give it explicitly anyway. (Lots of `{C = C}` in the code).
  - [ ] Can cokernels be defined as kernels in `C ^op`? (Don't repeat yourself)
- [ ] Make it easier to work with - I'm currently trying to define an example (Ab) of an abelian category, but it is quite messy. Some refactoring might make this nicer.
- [ ] Add a file `Categories/Abelian.agda`
- [ ] Clean up following style guide / [CONTRIBUTING.md](https://github.com/agda/cubical/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mortberg** [comment]
I'm currently working on fixing https://github.com/agda/cubical/issues/625 which will change pretty much all of the CT code. So you'll need to rebase this branch on master and fix conflicts once I've finished the big rewrite. 

For code that is not ready to be merged please use the "Draft Pull Request" feature: https://github.blog/2019-02-14-introducing-draft-pull-requests/

Finally, thanks for adding this code! I can try to take a look soon. Are you working with Thierry on this?

**Comment by barrettj12** [comment]
This was @felixwellen's idea. I was unsure about the `Precategory`/`Category` distinction so it will be nice to have that cleared up.

**Comment by barrettj12** [comment]
@mortberg I have done a lot of changes/refactoring, so this PR is not really relevant anymore. Once you merge #629, I will PR what I've done in a piecemeal fashion. It will be easier just to create new PRs.

**Comment by mortberg** [comment]
Great! It's always easier to review smaller PRs doing on thing. I've merged https://github.com/agda/cubical/pull/629 now

**Pull request closed without merging**
