### PR TITLE
Eilenberg maclane spaces

### PR DESCRIPTION
**Pull request by felixwellen**
I am trying to copy Urlik Buchholtz' work on Eilenberg-MacLane space in #394

### CODE REVIEW

**Comment by mortberg** [comment]
What is the problem?

**Comment by felixwellen** [comment]
That's what I get, when I try to check Cubica/HITs/EMSpace/Properties.agda

image

**Comment by felixwellen** [comment]
I thought you might just know what this is about. E.g. did 'SquareP' change in the last month?

**Comment by mortberg** [comment]
Those few lines seem to have been edited by this PR: https://github.com/agda/cubical/pull/420/files

Maybe this is relevant as well: https://github.com/agda/cubical/pull/438/files#diff-a4dbf965013dcc2915fd866dc2584347fbb37453eada6d46dfd6ffb7092f828aR146

I'm not really sure what the problem might be

**Comment by ecavallo** [comment]
There's a function `isSet→SquareP` in `Foundations.HLevels` that'll close the last metas in `Properties`.

**Comment by felixwellen** [comment]
Thanks @ecavallo ! That works really nice :-)

**Pull request closed without merging**
