### PR TITLE
Html in gh-pages

### PR DESCRIPTION
**Pull request by ice1000**
Blah

### CODE REVIEW

**Comment by ice1000** [comment]
image

Any admin can help me clicking this button and select 'gh-pages'? The generation should be set up successfully.

**Comment by ice1000** [comment]
https://github.com/agda/cubical/tree/gh-pages

**Comment by Saizan** [comment]
Done

**Comment by ice1000** [comment]
https://agda.github.io/cubical/Cubical.Algebra.CommAlgebra.Ideal

**Comment by brendanzab** [comment]
yayyyy thanks @ice1000!

**Comment by brendanzab** [comment]
Might be a good idea to put https://agda.github.io/cubical/Cubical.README.html in the repostory metadata now :)

**Comment by mortberg** [comment]
> Might be a good idea to put https://agda.github.io/cubical/Cubical.README.html in the repository metadata now :)

Yes, can someone make a PR?

**Comment by brendanzab** [comment]
Oh, was more suggesting via the adding it to the repo via the web UI:

Screen Shot 2022-01-04 at 9 43 03 pm

**Comment by felixwellen** [comment]
The CI runs on my PRs from today fail with some error message containing "github-pages-deploy-action". Is this related to this PR's changes?
See:
https://github.com/agda/cubical/runs/4704441227?check_suite_focus=true

**Comment by brendanzab** [comment]
Hmm, it's odd that the pages deployment is being done on CI runs - not sure if that is part of it? I generally put it in a separate workflow that only runs when pushing to the default branch (see the different `ci.yml`/`cd.yml` files [here](https://github.com/brendanzab/ocaml-flake-example/tree/main/.github/workflows)). That way you don't randomly see changes whenever tests are run on a PR branch. Not sure that is the cause of the failure though.

**Comment by ice1000** [comment]
> Hmm, it's odd that the pages deployment is being done on CI runs - not sure if that is part of it? I generally put it in a separate workflow that only runs when pushing to the default branch (see the different `ci.yml`/`cd.yml` files [here](https://github.com/brendanzab/ocaml-flake-example/tree/main/.github/workflows)). That way you don't randomly see changes whenever tests are run on a PR branch. Not sure that is the cause of the failure though. 

It is very expensive to install agda so I just changed the test. I think I know the cause and I'll try to fix it

**Comment by ice1000** [comment]
My guess is that the workflow relies on the pusher's access towards the repo, so @brendanzab 's suggestion should fix it if I'm right

**Comment by brendanzab** [comment]
> It is very expensive to install agda so I just changed the test. I think I know the cause and I'll try to fix it

Hmm, I wonder if you could do something like:

```yaml
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref_name == 'master'
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: html
```

**Pull request merged**
