### PR TITLE
Mayer-Vietoris cofiber sequence

### PR DESCRIPTION
**Pull request by ecavallo**
Translating a result from my master's thesis into cubical type theory. I don't have any endgame for this, I just wanted to try it.

### CODE REVIEW

**Comment by mortberg** [comment]
How does the complexity of the proofs differ from the HoTT proofs?

@aljungstrom : is this something you could have use for?

**Comment by aljungstrom** [comment]
> @aljungstrom : is this something you could have use for?
Ah, yes, possibly!

**Comment by ecavallo** [comment]
> How does the complexity of the proofs differ from the HoTT proofs?

The HoTT-Agda proof is here: https://github.com/HoTT/HoTT-Agda/blob/master/theorems/homotopy/CofiberSequence.agda
Even in HoTT I was using cubical-style box-filling lemmas, so it's not _that_ different.

**Comment by mortberg** [comment]
Merging this now, thanks for the contribution!

**Pull request merged**
