### PR TITLE
A direct proof of ΣProp≡ without Σ≡

### PR DESCRIPTION
**Pull request by L-TChen**
In order to prove that the type of n-types is an (n+1) type, I come up with a direct proof of  `ΣProp≡`.

### CODE REVIEW

**Comment by mortberg** [comment]
Great! I think the reason I wanted another proof of this was so that we could then reorganize some other things. But I don't remember what anymore...

**Comment by L-TChen** [comment]
By the way, where shall I put the proof that the type of n-types is an (n+1) type? 

`Data.Sigma.Properties` depends on `Foundations.HLevels`, but naturally `ΣProp≡` used in the proof should be in `Data.Sigma.Properties`...

**Comment by mortberg** [comment]
> By the way, where shall I put the proof that the type of n-types is an (n+1) type?
> 
> `Data.Sigma.Properties` depends on `Foundations.HLevels`, but naturally `ΣProp≡` used in the proof should be in `Data.Sigma.Properties`...Perhaps it is the reason why you need direct proof?

Yes! That's it! With your new proof we should be able to put both results in HLevels.

**Comment by mortberg** [comment]
So please move `ΣProp≡` and `HLevel≡` to `Cubical.Foundations.HLevels`.

Please also take a look in `Cubical.Foundations.HAEquiv``and move whatever can be moved upstream after "TODO: all of these should be moved". I think those results ended up there only because of the dependence on Data.Sigma in that file.

**Comment by L-TChen** [comment]
Done. But the following properties are moved to Prelude as I don't find a better place for them

* isPropIsContr
* isContr→isProp
* isProp→isSet

How about having a Prelude.Properties for h-level properties lower than or equal to `Set`?

**Comment by L-TChen** [comment]
> By the way, where shall I put the proof that the type of n-types is an (n+1) type?

The proof was in HAEquiv ... Anyway, they are already moved to HLevel, so I don't have to prove again it myself. Hooray.

**Comment by L-TChen** [comment]
Proofs in HLevels, I think, can be simplified or changed so that more dependencies can be removed. For example,  `congEquiv` in HAEquiv is used only once to prove that h-level is closed under equivalence, but the proof (Thm 7.1.4) in HoTT book uses that a retract of a n-type is n-type which is missing in HLevel. 

For now, I'd like to leave it as it is. Maybe make it an issue so we can come back later.

**Comment by mortberg** [comment]
> Proofs in HLevels, I think, can be simplified or changed so that more dependencies can be removed. For example, `congEquiv` in HAEquiv is used only once to prove that h-level is closed under equivalence, but the proof (Thm 7.1.4) in HoTT book uses that a retract of a n-type is n-type which is missing in HLevel.
> 
> For now, I'd like to leave it as it is. Maybe make it an issue so we can come back later.

Indeed, the best way to prove this kind of lemma is typically to use the fact that if X is a retract of Y and Y is an n-type then X is. I've been very busy lately with other things so I haven't had time to sort out the best way to do these proofs for this library, so I very much appreciate that you are helping out with untangling these dependencies.

**Comment by L-TChen** [comment]
> > Proofs in HLevels, I think, can be simplified or changed so that more dependencies can be removed. For example, `congEquiv` in HAEquiv is used only once to prove that h-level is closed under equivalence, but the proof (Thm 7.1.4) in HoTT book uses that a retract of a n-type is n-type which is missing in HLevel.
> > For now, I'd like to leave it as it is. Maybe make it an issue so we can come back later.
> 
> Indeed, the best way to prove this kind of lemma is typically to use the fact that if X is a retract of Y and Y is an n-type then X is. I've been very busy lately with other things so I haven't had time to sort out the best way to do these proofs for this library, so I very much appreciate that you are helping out with untangling these dependencies.

My pleasure!

**Pull request merged**
