### PR TITLE
Algebraic geometry directory, take 2

### PR DESCRIPTION
**Pull request by mzeuner**
Redoing https://github.com/agda/cubical/pull/1100, which seemed easier than fixing all the merge conflicts...

### CODE REVIEW

**Comment by mortberg** [comment]
Nice! Is this ready to be merged or do you want to make any more changes?

**Review by mortberg — APPROVED** [review]

**Comment by mzeuner** [comment]
Maybe @MatthiasHu  or @felixwellen have something the would like to add or change?

**Comment by felixwellen** [comment]
Yes, good! I think it is better to have more references when in doubt.

**Comment by mortberg** [comment]
> Yes, good! I think it is better to have more references when in doubt.

Should we merge?

**Comment by mzeuner** [comment]
Fixed a technicality in the comments, should be good to merge now.

**Pull request merged**
