### PR TITLE
Organize rings and commutative rings into categories

### PR DESCRIPTION
**Pull request by mortberg**
Need to upstream some code, so draft for now. Can any of the lemmas about (comm)ring homomorphisms be found anywhere in the library @mzeuner @felixwellen ?

### CODE REVIEW

**Comment by felixwellen** [comment]
I wouldn't know that any of these have been proved elsewhere. Maybe it would be better to move them to 'Ring/Properties' or something like that, so they won't get reproved accidentally.
One small remark about something completely different: It might be better to call the instance of a Category 'Rings', since you can also view a single ring as a category.

**Comment by mortberg** [comment]
Ah, good point! I'll rename the files and upstream the ring lemmas.

**Comment by mortberg** [comment]
I think this is ready for review @felixwellen . Hopefully nothing too contorversial

**Comment by felixwellen** [comment]
Looks good to me. Is there a reason things are different for Ring and CommRing? I means, in the definition of the precategory Rings agda seems to need less information than with CommRings. Also, the lemmas you use look a bit different.

**Comment by mortberg** [comment]
> Looks good to me. Is there a reason things are different for Ring and CommRing? I means, in the definition of the precategory Rings agda seems to need less information than with CommRings. Also, the lemmas you use look a bit different.

The problem is that homomorphisms for CommRings are defined in terms of homomorphisms of Rings. By projecting from CommRing to Ring Agda gets confused sometimes and we need to provide more arguments explicitly... It might be that a direct definition of what a CommRing homomorphism is will be needed if the current definition gets too annoying

**Pull request merged**
