### PR TITLE
Show that Pi preserves all h-levels

### PR DESCRIPTION
**Pull request by dolio**
- Includes a used lemma that funExt is an equivalence/path

### CODE REVIEW

**Comment by mortberg** [comment]
Thank you for this nice contribution! I would be happy to merge if you just move the changes from Core/Glue to somewhere in Basics (maybe a new file or Basics/Equiv).

My plan is to keep the Core library as minimal as possible and keep all the basic theory in Basics.

**Comment by dolio** [comment]
Okay. Will do.

**Comment by dolio** [comment]
I moved it to Cubical.Basics.Function. Equiv would have created a cycle with NTypes.

**Comment by mortberg** [comment]
Great, thanks!

**Pull request merged**
