### PR TITLE
More copatterns in Cubical.Algebra

### PR DESCRIPTION
**Pull request by felixwellen**
Try to make things type-check faster by using copatterns everywhere.
However, nothing got faster so far...

### CODE REVIEW

**Comment by thomas-lamiaux** [comment]
This file couldn't be type checked without the flag --loosy-experimentation.
Maybe here it would help ?
https://github.com/agda/cubical/blob/master/Cubical/Algebra/Polynomials/Multivariate/EquivCarac/Polyn-nPoly.agda

**Comment by thomas-lamiaux** [comment]
@felixwellen I didn't understood, do you want to merge this after of before the renaming one ?

**Comment by felixwellen** [comment]
Thanks for reminding - I think we decided to merge this now (yesterday, so I'll do that after checking that it type checks with newest master...

**Comment by mortberg** [comment]
Looks good to me!

**Pull request merged**
