### PR TITLE
A more compact uaβ

### PR DESCRIPTION
**Pull request by 3abc**

### CODE REVIEW

**Comment by 3abc** [comment]
> I think the hcomp's should all go away with `ghcomp` right?

Just to confirm, is `ghcomp` the one mentioned at https://github.com/agda/agda/issues/3415?

**Comment by mortberg** [comment]
Yes, I should really try to implement ghcomp. It should hopefully make working in Cubical Agda both easier and more efficient

**Comment by 3abc** [comment]
> I intentionally proved this the verbose way to make it clear what is going on, but it makes sense to also have the version with shorter proof term. Maybe we can keep the old version in a comment?

The old version wasn't very readable to me. If you want a version that shows what's going on, how about putting this in comment:

```
uaβ' : ∀ {ℓ} {A B : Set ℓ} (e : A ≃ B) (x : A)
      → transp (λ i → ua e i) i0 x ≡ e .fst x
uaβ' {A = A} {B = B} e x =
  transp (λ i → ua e i) i0 x
         ≡⟨ refl ⟩
  hthtfx ≡⟨ h-id thtfx ⟩
  thtfx  ≡⟨ t-id htfx ⟩
  htfx   ≡⟨ h-id tfx ⟩
  tfx    ≡⟨ t-id fx ⟩
  fx ∎
  where
  f = e .fst
  t : B → B
  t x = transp (λ _ → B) i0 x
  t-id : (x : B) → t x ≡ x
  t-id x = λ j → transp (λ _ → B) j x
  h : B → B
  h x = hcomp (λ _ → empty) x
  h-id : (x : B) → h x ≡ x
  h-id x = (λ j → hfill (λ _ → empty) (inc x) (~ j))
  fx = f x
  tfx = t fx
  htfx = h tfx
  thtfx = t htfx
  hthtfx = h thtfx```

**Comment by ice1000** [comment]
> you may want to replace tabs with spaces

**Comment by ice1000** [comment]
Actually I don't see any tabs in the file

**Comment by mortberg** [comment]
Very strange, I restarted the build

**Comment by mortberg** [comment]
I fixed the issue. Let's see if Travis is happy

**Pull request merged**
