### PR TITLE
Import basics on modalities from HoTT-Agda

### PR DESCRIPTION
**Pull request by felixwellen**
Define modalities and prove the following basic facts:

* Modalities preserve equivalences

* Pi types of modal dependent types are modal

* Sigmas of modal dependent types on a modal type are modal

### CODE REVIEW

**Comment by jonsterling** [comment]
Excellent! Funnily enough, I just spent the day getting owned by being confused about how modalities work :laughing:

**Comment by felixwellen** [comment]
I'm happy to discuss modalities next week, when I'm back in Pittsburgh. There is also a lot to formalize, I just did some basics. I guess I should make a list and open an issue.

**Comment by felixwellen** [comment]
I should have had coffee first;)

**Comment by Alizter** [comment]
LGTM I think the next thing to do would be to redefine truncations in terms of modalities. That will act as a test case if you will.

**Comment by felixwellen** [comment]
I see three things that could be done (concerning truncations):
1) Show that the (already defined) truncations are modalities.
2) Define truncations as nullification modalities.
3) Show that these two are the same.
The first one could be based directly on this PR. It might be a good idea to prove a suitable characterization of modalities first. Everyone is welcome to do this - I will work on other things first.
I'm still working on the localization/nullification needed for 2) (and indirectly for 3). I certainly don't insist on doing this alone...

**Comment by mortberg** [comment]
> I see three things that could be done (concerning truncations):
> 
>     1. Show that the (already defined) truncations are modalities.
> 
>     2. Define truncations as nullification modalities.
> 
>     3. Show that these two are the same.
>        The first one could be based directly on this PR. It might be a good idea to prove a suitable characterization of modalities first. Everyone is welcome to do this - I will work on other things first.
>        I'm still working on the localization/nullification needed for 2) (and indirectly for 3). I certainly don't insist on doing this alone...

Great! How about making issues for each of these? That way you or someone else can assign themselves and the specific project can be discussed in the issue.

**Pull request merged**
