### PR TITLE
Renamed inc/ouc to inS/outS.

### PR DESCRIPTION
**Pull request by Saizan**

### CODE REVIEW

**Comment by jonsterling** [comment]
How about `inS/auS`? :sunglasses:

**Comment by Saizan** [comment]
Ok, unless any other PRs are ready today and could go first.

**Comment by 3abc** [comment]
How about Agda internals? Are they going to change? I assume now when one normalizes things one still gets `inc` `ouc`'s in the information window?

**Comment by Saizan** [comment]
@3abc that shouldn't happen, because it's been done with the `renaming` feature.

**Comment by 3abc** [comment]
> @3abc that shouldn't happen, because it's been done with the `renaming` feature.

What is that? Any reference?

**Comment by Saizan** [comment]
https://agda.readthedocs.io/en/v2.5.4.2/language/module-system.html#name-modifiers

**Pull request merged**
