### PR TITLE
Type-theoretic replacement with higher induction-recursion

### PR DESCRIPTION
**Pull request by ecavallo**
A nice way to construct it quickly, though it uses a stronger tool than is necessary.

### CODE REVIEW

**Comment by mortberg** [comment]
Nice! Please add an equivalence with the image that already exist in `Functions.Image`. Maybe also add a simpler construction for sets?

**Comment by ecavallo** [comment]
I proved the equivalence (actually uniqueness of image factorizations more generally). The case for sets I think can wait for another PR.

**Comment by felixwellen** [comment]
All good now -> merging.

**Comment by felixwellen** [comment]
Hope it works with current master...

**Pull request merged**
