### PR TITLE
Function properties

### PR DESCRIPTION
**Pull request by m-yac**
It felt strange that I had to define `id` and `const` myself when using this library. I added these functions and some basic properties about composition to `Cubical.Foundations.Function`.

### CODE REVIEW

**Comment by 3abc** [comment]
> It felt strange that I had to define `id` and `const` myself when using this library. I added these functions and some basic properties about composition to `Cubical.Foundations.Function`.

There is `idfun` defined in `Glue.agda`. Not sure about the constant function.

```
Cubical/Core/Glue.agda
75:idfun : ∀ {ℓ} → (A : Set ℓ) → A → A
76:idfun _ x = x
```

**Comment by m-yac** [comment]
> There is `idfun` defined in `Glue.agda`.

Ah! Though looks like `idFun` has an explicit type argument, is it worth having a duplicate with this argument implicit?

**Comment by 3abc** [comment]
> Ah! Though looks like `idFun` has an explicit type argument, is it worth having a duplicate with this argument implicit?

I don't know, ask @mortberg .

**Comment by mortberg** [comment]
> > Ah! Though looks like `idFun` has an explicit type argument, is it worth having a duplicate with this argument implicit?
> 
> I don't know, ask @mortberg .

It doesn't sound reasonable to have a duplicate of this. Can you make the type implicit in `idfun` without things breaking (after adapting the places where it is used)?

**Comment by 3abc** [comment]
> > > Ah! Though looks like `idFun` has an explicit type argument, is it worth having a duplicate with this argument implicit?
> > 
> > 
> > I don't know, ask @mortberg .
> 
> It doesn't sound reasonable to have a duplicate of this. Can you make the type implicit in `idfun` without things breaking (after adapting the places where it is used)?

I just took a look, a lot of time if we make thing explicit we will need to write things like `idfun {A = B}`. Not sure if it is worth it.

**Comment by mortberg** [comment]
> > > > Ah! Though looks like `idFun` has an explicit type argument, is it worth having a duplicate with this argument implicit?
> > > 
> > > 
> > > I don't know, ask @mortberg .
> > 
> > 
> > It doesn't sound reasonable to have a duplicate of this. Can you make the type implicit in `idfun` without things breaking (after adapting the places where it is used)?
> 
> I just took a look, a lot of time if we make thing explicit we will need to write things like `idfun {A = B}`. Not sure if it is worth it.

Right, that's what I seem to remember. So let's keep only idfun the way it is.

**Comment by m-yac** [comment]
> So let's keep only idfun the way it is.

2d91e62 Is this what you had in mind?

Looking at `Cubical.Core.Glue` I agree that the explicit argument is needed.

**Comment by mortberg** [comment]
Yeah, this looks good now! Thanks for contributing

**Pull request merged**
