### PR TITLE
Uniqueness of Final and Initial Objects

### PR DESCRIPTION
**Pull request by kl-i**
Is uniqueness of final/initial objects up to equality (for univalent categories) in the library? If not, I have written a proof. 

(Apologies if I'm writing in the wrong place, as a pen-and-paper maths guy, I've never made a git pull request before.)

### CODE REVIEW

**Comment by ecavallo** [comment]
Hi! I don't think it is in the library and we would be happy to have your proof; sorry about the long wait.

It looks like you've made a PR from an unrelated branch ([cubical/agda5803](https://github.com/agda/cubical/tree/agda5803)). I didn't see a fork of agda/cubical among your repos, do you know where your code is? The usual workflow would be that you make a fork of cubical, push changes to a branch on that fork, then make a pull request to merge your branch into our cubical/master.

**Comment by kl-i** [comment]
I shall make a copy of the newest version of the repo and put my code, then try forking.

**Comment by kl-i** [comment]
I have made a copy of cubical-0.4 and use `make` to check my code doesn't break anything. I'm not sure what I should do from here?

**Comment by ecavallo** [comment]
I believe if you go to https://github.com/kl-i/cubical-0.4 you'll see a "Contribute" menu that will let you open a pull request.

**Pull request closed without merging**
