### PR TITLE
Compute free algebra on empty type

### PR DESCRIPTION
**Pull request by felixwellen**
Compute that R[ ⊥] is R itsself.
Also move and split FreeCommAlgebra in the process.

### CODE REVIEW

**Comment by mortberg** [comment]
@felixwellen : Can you fix the conflict? 

Sorry for the slow review, I think the code looks fine and would be happy to merge

**Review by mortberg — APPROVED** [review]

**Comment by mortberg** [comment]
Looks like you missed one conflict?

**Comment by mortberg** [comment]
Or maybe it appeared after I just merged the other PR...

**Comment by felixwellen** [comment]
I guess I was just trying to do too many things in parallel.... I'll try to fix it.

**Pull request merged**
