### PR TITLE
Changes related to a change to Agda's reflection machinery.

### PR DESCRIPTION
**Pull request by nad**
See https://github.com/agda/agda/issues/5317.

### CODE REVIEW

**Comment by ecavallo** [comment]
Is there a reason this change is to the [2ltt-simpler](/github/agda/cubical/2ltt-simpler) branch instead of [master](/github/agda/cubical/master)?

**Comment by Saizan** [comment]
I expect that's because what agda/master tests against

**Comment by nad** [comment]
Agda's cubical library submodule is currently at commit e8aa103cc3ac9ff69c8e3ece274b0db17aec50d1, which matches the 2ltt-simpler branch. I don't know if there is any plan behind this.

Given that the code will not work with the current release of Agda I suspect that you do not want to have it on the main branch at the moment.

**Comment by ecavallo** [comment]
Ah, OK.

**Pull request merged**
