### PR TITLE
Add Ab as instance of category

### PR DESCRIPTION
**Pull request by barrettj12**

### CODE REVIEW

**Review by mortberg — APPROVED** [review]
LGTM

**Comment by mortberg** [comment]
Wait a minute... To be consistent with naming this should be `AbGroupCategory`.

We might consider better naming for instances at some point... But for now let's try to be consistent with the arguably bad naming

**Comment by barrettj12** [comment]
I can change it if you like. However, I do think there is an argument to be made that we should give them their conventional names (**Set**, **Grp**, **Ring**, **Cat**, **Ab**, etc)

**Comment by mortberg** [comment]
> I can change it if you like. However, I do think there is an argument to be made that we should give them their conventional names (**Set**, **Grp**, **Ring**, **Cat**, **Ab**, etc)

Yup, the name of Set and functor categories currently doesn't follow any convention either. We also have instances for algebraic structure that follow different conventions... We should decide for a convention and rename all of these consistently.

**Comment by barrettj12** [comment]
> We should decide for a convention and rename all of these consistently.

Good idea, I can open an issue on this.

**Comment by mortberg** [comment]
> > We should decide for a convention and rename all of these consistently.
> 
> Good idea, I can open an issue on this.

Yes, please!

**Pull request merged**
