### PR TITLE
generalize levels for some AlgebraHom operations

### PR DESCRIPTION
**Pull request by MatthiasHu**
This PR just generalizes the type signatures of operations like `AlgebraHom≡` or `_∘≃a_` to algebras of different levels.

EDIT: Also, use declared variables as much as possible.

### CODE REVIEW

**Review by felixwellen — CHANGES_REQUESTED** [review]
Did you try to use generalized variables (for R, A, B, C, D) - that should be a lot simpler?
If yes, then it would be good to have a comment explaining why it doesn't work.

**Comment by MatthiasHu** [comment]
This is better, thank you for pointing it out.

In `Algebra.Base`, it is not so easy to do consistently. Does it look ok the way it is now?

**Comment by felixwellen** [comment]
Yes, looks good to me.

**Review by felixwellen — APPROVED** [review]

**Comment by felixwellen** [comment]
Now it just needs to pass ci...

**Pull request merged**
