### PR TITLE
Add alternative builders for groups.

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by Alizter** [comment]
I don't think the *definition* of a group should be changed but rather a better constructor should be used. This is similar to how we can adjointify equivalences but the definition of a half-adjoint equivalence still has the extra data.

**Comment by WorldSEnder** [comment]
I agree with @Alizter . Sometimes you get better computational behaviour when you specify the paths directly. Say you have a group where `comp` computes nicely and `lCancel` is just true by `refl`. Why should one be forced to have `lCancel` be a large path composition - even abstract in this PR! Additionally, it's rather arbitrary to chose `lCancel` instead of `rCancel`.

**Comment by Saizan** [comment]
I would lean towards keeping `lUnit` and `lCancel` in the record and providing a function that builds a group without asking for those.

**Comment by mortberg** [comment]
> I would lean towards keeping `lUnit` and `lCancel` in the record and providing a function that builds a group without asking for those.

Ok, let's do that!  @favonia : can you please implement this?

**Comment by mortberg** [comment]
Great! I really like the names for the group constructors

**Comment by favonia** [comment]
The master branch is broken now.

**Comment by mortberg** [comment]
Yup... And I don't have agda installed on this computer so it will take me a few hours to fix it. Can anyone else do it?

**Comment by mortberg** [comment]
I think the bug comes from me redefining the recursor for truncation without taking into account the cohomology PR...

**Pull request merged**
